<?php

require_once  'vendor/autoload.php';

ob_start();

?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Report</title>
	<style>
		table {
			border-collapse: collapse;
			border: 1px solid black;
		}

		tr {
			border: 1px solid black;
		}

		td {
			border: 1px solid black;

			text-align: center;
		}
	</style>



</head>

<body>
	<h1>Transaction Report</h1>
	<!-- <?php print_r($get_pdf_data); ?> -->

	<div class="row p-t-40">
		<div class="col">
			<div id="myTable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
				<div class="row">
					<div class="col-sm-12 col-md-6">

						<div class="col-sm-12 col-md-6">
							<!-- <div id="myTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="myTable"></label></div> -->
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">


							<table class="table table-bordered table-responsive" width="100%">
								<thead>
									<tr>
										<td width="4%">
											<p>S.No</p>
										</td>
										<td width="5%">
											<p>HCF With Address</p>
										</td>
										<td width="4%">
											<p>Type Of HCf</p>
										</td>
										<td colspan="9" width="38%">
											Details Of Bio Medical Generated By HCF (Qty. Of BMW in K.g)
										</td>
										<td colspan="9" width="39%">
											Details Of Bio Medical Received By CBWTF (Qty. Of BMW in K.g)
										</td>
										<td width="7%">
											<p>Difference (Qty. in K.g)</p>
										</td>
									</tr>
									<tr>
										<td width="4%">
											<p> </p>
										</td>
										<td width="5%">
											<p>&nbsp;</p>
										</td>
										<td width="4%">
											<p>&nbsp;</p>
										</td>
										<td rowspan="2" width="8%">
											Date Time
										</td>
										<td colspan="2" width="9%">
											<p>Yellow</p>
										</td>
										<td colspan="2" width="9%">
											<p>Red</p>
										</td>
										<td colspan="2" width="9%">
											<p>White</p>
										</td>
										<td colspan="2" width="9%">
											<p>Blue</p>
										</td>
										<td width="8%">
											Date Time
										</td>
										<td colspan="2" width="7%">
											<p>Yellow</p>
										</td>
										<td colspan="2" width="7%">
											<p>Red</p>
										</td>
										<td colspan="2" width="7%">
											<p>White</p>
										</td>
										<td colspan="2" width="8%">
											<p>Blue</p>
										</td>
										<td width="7%">

										</td>
									</tr>
									<tr>
										<td width="4%">

										</td>
										<td width="5%">

										</td>
										<td width="4%">

										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt.</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>&nbsp;</p>
										</td>

										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="3%">
											<p>Qnt</p>
										</td>
										<td width="4%">
											<p>No. of Bags</p>
										</td>
										<td width="4%">
											<p>Qnt</p>
										</td>

									</tr>
								</thead>


								<tbody>
									<?php
									$i = 1;
									foreach ($get_pdf_data as $row) {
									?>
										<tr>
											<td width="4%">
												<?php echo $i; ?>
											</td>
											<td width="5%">
												<p><?php echo $row['org_name'] . ',<br>' . $row['address']; ?></p>
											</td>
											<td width="4%">
												<p><?php echo $row['medical_type']; ?></p>
											</td>
											<td width="4%">
												<?php echo $row['collection_date']; ?>
											</td>
											<?php  ?>
											<td width="4%">
												<?php
												echo $row['yellow_count'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['yellow_weight'], 2);
												?>
											</td>
											<td width="3%">
												<?php
												echo $row['red_count'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['red_weight'], 3);
												?>
											</td>

											<td width="3%">
												<?php
												echo $row['white_count'];
												?>
												<!-- <td width="4%"> -->

											</td>
											<td width="3%">
												<?php
												echo round($row['white_weight'], 3);
												?>
											</td>
											<td width="4%">
												<?php
												echo $row['blue_count'];
												?>
											</td>
											<td width="3%">
												<?php
												echo round($row['blue_weight'], 3);
												?>
											</td>
											<td width="4%">
												<?php
												if ($row['treatment_date'] == 0) {
													echo "<span style='color:red;'>Pending</span>";
												} else {
													echo $row['treatment_date'];
												}

												?>
											</td>
											<td width="4%">
												<?php
												echo $row['yellow_count2'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['yellow_weight2'], 3);
												?>
											</td>
											<td width="3%">
												<?php
												echo $row['red_count2'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['red_weight2'], 3);
												?>
											</td>
											<td width="3%">
												<?php
												echo $row['white_count2'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['white_weight2'], 3);
												?>
											</td>
											<td width="3%">
												<?php
												echo $row['blue_count2'];
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['blue_weight2'], 3);
												?>
											</td>
											<td width="4%">
												<?php
												echo round($row['weight1'] - $row['weight2'], 3);
												?>
											</td>

										</tr>


									<?php
										$i++;
									}
									?>

								</tbody>
							</table>
						</div>
					</div>




</body>

</html>






<?php
$Output = ob_get_contents();
ob_end_clean();
// $mpdf = new \Mpdf\Mpdf();
// $mpdf->WriteHTML();
// $mpdf->Output();


// $mpdf = new \Mpdf\Mpdf();

// $mpdf->WriteHTML($Output);
// $mpdf->SetWatermarkText("BMW");
// $mpdf->showWatermarkText = true;
// $mpdf->watermarkTextAlpha = 0.1;
// $mpdf->Output("report.pdf", 'I');
// $mpdf->SetDisplayMode('fullpage');

$mpdf = new \Mpdf\Mpdf(['format' => 'A4-L']);
$mpdf->WriteHTML($Output);

$mpdf->SetWatermarkText("Bio Medical Waste Management");
$mpdf->showWatermarkText = true;
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->Output('report.pdf', 'D');


?>